/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h> // Потрібна для функції sprintf
#include "stm32f4xx.h"
#include "RCC_comf.h"

void ADC_init(){

	//Вмикаємо RCC для GPIO та ADC
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;

	//GPIO в аналоговий режим
	GPIOA->MODER |= (0b11 << 2);

	//Sample time
	ADC1->SMPR2 &= ~(0b111 << 3);

	//Resolution
	ADC1->CR1 &= ~(0b11 << 24);

	//Number of chanel
	ADC1->SQR1 &= ~(0b1111 << 20);

	//Sequence of channel
	ADC1->SQR3 |= 1;

	//Continuous mode
	ADC1->CR2 |= ADC_CR2_CONT;

	//ADC прескалер
	ADC->CCR &= ~(0b11 << 16);

	//Вмикаємо ADC1
	ADC1->CR2 |= ADC_CR2_ADON;

	for(volatile int i = 0; i < 1000; i++);

	//Запускаємо ADC
	ADC1->CR2 |= ADC_CR2_SWSTART;
}

void UART1_Init(void) {
    // 1. Вмикаємо тактування GPIOA та USART1
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
    RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

    // 2. Налаштовуємо пін PA9 (TX) на Альтернативну Функцію (AF)
    GPIOA->MODER &= ~GPIO_MODER_MODER9;   // Очищаємо біти
    GPIOA->MODER |= GPIO_MODER_MODER9_1;  // Встановлюємо 10 (Alternate function)

    // 3. Вказуємо, що ця альтернативна функція - це саме USART1.
    // Для USART1 це функція AF7. Записуємо 7 у регістр AFRH (AFR[1]) для 9-го піна.
    GPIOA->AFR[1] |= (7 << 4);

    // 4. Налаштовуємо швидкість (Baudrate) = 115200.
    // Формула: 72 000 000 / 115200 = 625 (округлюємо до 625).
    USART1->BRR = 625;

    // 5. Вмикаємо передавач (TE) та сам модуль USART (UE)
    USART1->CR1 |= USART_CR1_TE | USART_CR1_UE;
}

// Функція для відправки одного символу
void UART_SendChar(char c) {
    // Чекаємо, поки буфер передавача звільниться (TXE = Transmit Data Register Empty)
    while (!(USART1->SR & USART_SR_TXE));
    USART1->DR = c; // Відправляємо символ
}

// Функція для відправки цілого рядка тексту
void UART_SendString(char* str) {
    while (*str) {
        UART_SendChar(*str++);
    }
}

int main(void)
{
	RCC_init();
	ADC_init();
	UART1_Init();

	// Масив (буфер) для формування текстового повідомлення
	char msg_buffer[50];
	volatile uint16_t my_adc_value = 0;
	while(1){
		while(!(ADC1->SR & (1 << 1)));
		my_adc_value = ADC1->DR;

		sprintf(msg_buffer, "ADC Value: %d\r\n", my_adc_value);

		// 3. Відправляємо сформований текст у термінал
		UART_SendString(msg_buffer);

		//for(volatile uint32_t i = 0; i < 500000; i++);
	}
}
